blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ğŸ½â€â™€ï¸ Getting help with code
    url: https://stackoverflow.com/questions/tagged/parse-platform+parse-javascript-sdk
    about: Get help with code-level questions on Stack Overflow.
  - name: ğŸ™‹ Getting general help
    url: https://community.parseplatform.org/c/client-sdks/javascript-sdk
    about: Get help with other questions on our Community Forum.
